### ISSUE TITLE
Charm with weird platform name breaks

### ISSUE THREAD

**Issue by lengau** [canonical/craft-platforms#116]
A charm with:

```yaml
base: ubuntu@24.04
platforms:
  "0:":
    build-on: [amd64]
    build-for: [amd64]
```

Raises `ValueError: Invalid base string '0'. Format should be '<distribution>@<series>'`.

First discovered at https://github.com/canonical/craft-platforms/actions/runs/14137328500/job/39612051861?pr=83#step:6:205
