### ISSUE TITLE
Vectorize `build-on` and `build-for`

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-platforms#80]
The build planners fail to create a build plan from the yaml:

```yaml
platforms:
  my-platform:
    build-on: amd64
    build-for: riscv64
```

This is a problem because craft-application is able to create a build plan but craft-platforms can't.  

Craft-application vectorizes `build-on` and `build-for` before providing the data to craft-platforms.
