### ISSUE TITLE
Allow `devel` in multi-base builds

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-platforms#85]
The charm build planner can't use `devel` build bases for multi-base builds.

One option would be to allow definitions like:

```yaml
platforms:
  plucky:
    build-on: [devel:amd64]
    build-for: [ubuntu@24.04:amd64]
```
